#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"
require "testswarm/client"

server  = ENV["TESTSWARM_SERVER"]
key     = ENV["TESTSWARM_KEY"]
root    = ENV["TESTSWARM_ROOT"]
bundle  = ENV["BUNDLE_DIRECTORY"]

client  = TestSwarm::Client.new(server)
project = client.project("faye", :auth => key)

job = TestSwarm::Job.create(
  :rcs        => {
    :type     => "git",
    :url      => "git://github.com/faye/faye.git",
    :branch   => "master"
  },
  :directory  => File.join(root, "changeset", project.name),
  :diff       => ["javascript", "spec/javascript"],
  :build      => [
                   "mkdir -p vendor",
                   "ln -s #{bundle} vendor/bundle",
                   "bundle install --path vendor/bundle",
                   "npm install",
                   "rm -rf build",
                   "bundle exec jake"
                 ],
  :inject     => "spec/browser.html"
)

exit unless job.new?

path = "#{client.url}/changeset/#{project.name}/#{job.revision}"
job.add_suite "Faye tests", "#{path}/spec/browser.html"

project.submit_job "Faye Commit #{job.revision}", job,
                   :browsers => "all",
                   :max      => 5

